<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('currencies')->delete();

        \DB::table('currencies')->insert([
            [
                'id' => 1,
                'name' => 'Leke',
                'country' => 'Albania',
                'code' => 'ALL',
                'symbol' => 'Lek',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'name' => 'Dollars',
                'country' => 'America',
                'code' => 'USD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'name' => 'Afghanis',
                'country' => 'Afghanistan',
                'code' => 'AF',
                'symbol' => '؋',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'name' => 'Pesos',
                'country' => 'Argentina',
                'code' => 'ARS',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'name' => 'Guilders',
                'country' => 'Aruba',
                'code' => 'AWG',
                'symbol' => 'ƒ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'name' => 'Dollars',
                'country' => 'Australia',
                'code' => 'AUD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'name' => 'New Manats',
                'country' => 'Azerbaijan',
                'code' => 'AZ',
                'symbol' => 'ман',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'name' => 'Dollars',
                'country' => 'Bahamas',
                'code' => 'BSD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'name' => 'Dollars',
                'country' => 'Barbados',
                'code' => 'BBD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'name' => 'Rubles',
                'country' => 'Belarus',
                'code' => 'BYR',
                'symbol' => 'p.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'name' => 'Euro',
                'country' => 'Belgium',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'name' => 'Dollars',
                'country' => 'Beliz',
                'code' => 'BZD',
                'symbol' => 'BZ$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'name' => 'Dollars',
                'country' => 'Bermuda',
                'code' => 'BMD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'name' => 'Bolivianos',
                'country' => 'Bolivia',
                'code' => 'BOB',
                'symbol' => '$b',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'name' => 'Convertible Marka',
                'country' => 'Bosnia and Herzegovina',
                'code' => 'BAM',
                'symbol' => 'KM',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'name' => 'Pula\'s',
                'country' => 'Botswana',
                'code' => 'BWP',
                'symbol' => 'P',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'name' => 'Leva',
                'country' => 'Bulgaria',
                'code' => 'BG',
                'symbol' => 'лв',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'name' => 'Reais',
                'country' => 'Brazil',
                'code' => 'BRL',
                'symbol' => 'R$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'name' => 'Pounds',
                'country' => 'Britain (United Kingdom)',
                'code' => 'GBP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'name' => 'Dollars',
                'country' => 'Brunei Darussalam',
                'code' => 'BND',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'name' => 'Riels',
                'country' => 'Cambodia',
                'code' => 'KHR',
                'symbol' => '៛',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'name' => 'Dollars',
                'country' => 'Canada',
                'code' => 'CAD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'name' => 'Dollars',
                'country' => 'Cayman Islands',
                'code' => 'KYD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'name' => 'Pesos',
                'country' => 'Chile',
                'code' => 'CLP',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'name' => 'Yuan Renminbi',
                'country' => 'China',
                'code' => 'CNY',
                'symbol' => '¥',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'name' => 'Pesos',
                'country' => 'Colombia',
                'code' => 'COP',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'name' => 'Colón',
                'country' => 'Costa Rica',
                'code' => 'CRC',
                'symbol' => '₡',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'name' => 'Kuna',
                'country' => 'Croatia',
                'code' => 'HRK',
                'symbol' => 'kn',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'name' => 'Pesos',
                'country' => 'Cuba',
                'code' => 'CUP',
                'symbol' => '₱',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'name' => 'Euro',
                'country' => 'Cyprus',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'name' => 'Koruny',
                'country' => 'Czech Republic',
                'code' => 'CZK',
                'symbol' => 'Kč',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'name' => 'Kroner',
                'country' => 'Denmark',
                'code' => 'DKK',
                'symbol' => 'kr',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'name' => 'Pesos',
                'country' => 'Dominican Republic',
                'code' => 'DOP ',
                'symbol' => 'RD$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'name' => 'Dollars',
                'country' => 'East Caribbean',
                'code' => 'XCD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'name' => 'Pounds',
                'country' => 'Egypt',
                'code' => 'EGP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'name' => 'Colones',
                'country' => 'El Salvador',
                'code' => 'SVC',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'name' => 'Pounds',
                'country' => 'England (United Kingdom)',
                'code' => 'GBP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'name' => 'Euro',
                'country' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'name' => 'Pounds',
                'country' => 'Falkland Islands',
                'code' => 'FKP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'name' => 'Dollars',
                'country' => 'Fiji',
                'code' => 'FJD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'name' => 'Euro',
                'country' => 'France',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'name' => 'Cedis',
                'country' => 'Ghana',
                'code' => 'GHC',
                'symbol' => '¢',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'name' => 'Pounds',
                'country' => 'Gibraltar',
                'code' => 'GIP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'name' => 'Euro',
                'country' => 'Greece',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'name' => 'Quetzales',
                'country' => 'Guatemala',
                'code' => 'GTQ',
                'symbol' => 'Q',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'name' => 'Pounds',
                'country' => 'Guernsey',
                'code' => 'GGP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'name' => 'Dollars',
                'country' => 'Guyana',
                'code' => 'GYD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'name' => 'Euro',
                'country' => 'Holland (Netherlands)',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'name' => 'Lempiras',
                'country' => 'Honduras',
                'code' => 'HNL',
                'symbol' => 'L',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'name' => 'Dollars',
                'country' => 'Hong Kong',
                'code' => 'HKD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'name' => 'Forint',
                'country' => 'Hungary',
                'code' => 'HUF',
                'symbol' => 'Ft',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'name' => 'Kronur',
                'country' => 'Iceland',
                'code' => 'ISK',
                'symbol' => 'kr',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'name' => 'Rupees',
                'country' => 'India',
                'code' => 'INR',
                'symbol' => 'Rp',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'name' => 'Rupiahs',
                'country' => 'Indonesia',
                'code' => 'IDR',
                'symbol' => 'Rp',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'name' => 'Rials',
                'country' => 'Iran',
                'code' => 'IRR',
                'symbol' => '﷼',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'name' => 'Euro',
                'country' => 'Ireland',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'name' => 'Pounds',
                'country' => 'Isle of Man',
                'code' => 'IMP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'name' => 'New Shekels',
                'country' => 'Israel',
                'code' => 'ILS',
                'symbol' => '₪',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'name' => 'Euro',
                'country' => 'Italy',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'name' => 'Dollars',
                'country' => 'Jamaica',
                'code' => 'JMD',
                'symbol' => 'J$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'name' => 'Yen',
                'country' => 'Japan',
                'code' => 'JPY',
                'symbol' => '¥',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 62,
                'name' => 'Pounds',
                'country' => 'Jersey',
                'code' => 'JEP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'name' => 'Tenge',
                'country' => 'Kazakhstan',
                'code' => 'KZT',
                'symbol' => 'лв',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'name' => 'Won',
                'country' => 'Korea (North)',
                'code' => 'KPW',
                'symbol' => '₩',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'name' => 'Won',
                'country' => 'Korea (South)',
                'code' => 'KRW',
                'symbol' => '₩',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'name' => 'Soms',
                'country' => 'Kyrgyzstan',
                'code' => 'KGS',
                'symbol' => 'лв',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'name' => 'Kips',
                'country' => 'Laos',
                'code' => 'LAK',
                'symbol' => '₭',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 68,
                'name' => 'Lati',
                'country' => 'Latvia',
                'code' => 'LVL',
                'symbol' => 'Ls',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 69,
                'name' => 'Pounds',
                'country' => 'Lebanon',
                'code' => 'LBP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 70,
                'name' => 'Dollars',
                'country' => 'Liberia',
                'code' => 'LRD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'name' => 'Switzerland Francs',
                'country' => 'Liechtenstein',
                'code' => 'CHF',
                'symbol' => 'CHF',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'name' => 'Litai',
                'country' => 'Lithuania',
                'code' => 'LTL',
                'symbol' => 'Lt',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 73,
                'name' => 'Euro',
                'country' => 'Luxembourg',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 74,
                'name' => 'Denars',
                'country' => 'Macedonia',
                'code' => 'MKD',
                'symbol' => 'ден',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 75,
                'name' => 'Ringgits',
                'country' => 'Malaysia',
                'code' => 'MYR',
                'symbol' => 'RM',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 76,
                'name' => 'Euro',
                'country' => 'Malta',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 77,
                'name' => 'Rupees',
                'country' => 'Mauritius',
                'code' => 'MUR',
                'symbol' => '₨',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 78,
                'name' => 'Pesos',
                'country' => 'Mexico',
                'code' => 'MX',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 79,
                'name' => 'Tugriks',
                'country' => 'Mongolia',
                'code' => 'MNT',
                'symbol' => '₮',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 80,
                'name' => 'Meticais',
                'country' => 'Mozambique',
                'code' => 'MZ',
                'symbol' => 'MT',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 81,
                'name' => 'Dollars',
                'country' => 'Namibia',
                'code' => 'NAD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 82,
                'name' => 'Rupees',
                'country' => 'Nepal',
                'code' => 'NPR',
                'symbol' => '₨',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 83,
                'name' => 'Guilders',
                'country' => 'Netherlands Antilles',
                'code' => 'ANG',
                'symbol' => 'ƒ',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 84,
                'name' => 'Euro',
                'country' => 'Netherlands',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 85,
                'name' => 'Dollars',
                'country' => 'New Zealand',
                'code' => 'NZD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 86,
                'name' => 'Cordobas',
                'country' => 'Nicaragua',
                'code' => 'NIO',
                'symbol' => 'C$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 87,
                'name' => 'Nairas',
                'country' => 'Nigeria',
                'code' => 'NG',
                'symbol' => '₦',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 88,
                'name' => 'Won',
                'country' => 'North Korea',
                'code' => 'KPW',
                'symbol' => '₩',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 89,
                'name' => 'Krone',
                'country' => 'Norway',
                'code' => 'NOK',
                'symbol' => 'kr',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 90,
                'name' => 'Rials',
                'country' => 'Oman',
                'code' => 'OMR',
                'symbol' => '﷼',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 91,
                'name' => 'Rupees',
                'country' => 'Pakistan',
                'code' => 'PKR',
                'symbol' => '₨',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 92,
                'name' => 'Balboa',
                'country' => 'Panama',
                'code' => 'PAB',
                'symbol' => 'B/.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 93,
                'name' => 'Guarani',
                'country' => 'Paraguay',
                'code' => 'PYG',
                'symbol' => 'Gs',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 94,
                'name' => 'Nuevos Soles',
                'country' => 'Peru',
                'code' => 'PE',
                'symbol' => 'S/.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 95,
                'name' => 'Pesos',
                'country' => 'Philippines',
                'code' => 'PHP',
                'symbol' => 'Php',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 96,
                'name' => 'Zlotych',
                'country' => 'Poland',
                'code' => 'PL',
                'symbol' => 'zł',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 97,
                'name' => 'Rials',
                'country' => 'Qatar',
                'code' => 'QAR',
                'symbol' => '﷼',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 98,
                'name' => 'New Lei',
                'country' => 'Romania',
                'code' => 'RO',
                'symbol' => 'lei',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 99,
                'name' => 'Rubles',
                'country' => 'Russia',
                'code' => 'RUB',
                'symbol' => 'руб',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 100,
                'name' => 'Pounds',
                'country' => 'Saint Helena',
                'code' => 'SHP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 101,
                'name' => 'Riyals',
                'country' => 'Saudi Arabia',
                'code' => 'SAR',
                'symbol' => '﷼',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 102,
                'name' => 'Dinars',
                'country' => 'Serbia',
                'code' => 'RSD',
                'symbol' => 'Дин.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 103,
                'name' => 'Rupees',
                'country' => 'Seychelles',
                'code' => 'SCR',
                'symbol' => '₨',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 104,
                'name' => 'Dollars',
                'country' => 'Singapore',
                'code' => 'SGD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 105,
                'name' => 'Euro',
                'country' => 'Slovenia',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 106,
                'name' => 'Dollars',
                'country' => 'Solomon Islands',
                'code' => 'SBD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 107,
                'name' => 'Shillings',
                'country' => 'Somalia',
                'code' => 'SOS',
                'symbol' => 'S',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 108,
                'name' => 'Rand',
                'country' => 'South Africa',
                'code' => 'ZAR',
                'symbol' => 'R',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 109,
                'name' => 'Won',
                'country' => 'South Korea',
                'code' => 'KRW',
                'symbol' => '₩',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 110,
                'name' => 'Euro',
                'country' => 'Spain',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 111,
                'name' => 'Rupees',
                'country' => 'Sri Lanka',
                'code' => 'LKR',
                'symbol' => '₨',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 112,
                'name' => 'Kronor',
                'country' => 'Sweden',
                'code' => 'SEK',
                'symbol' => 'kr',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 113,
                'name' => 'Francs',
                'country' => 'Switzerland',
                'code' => 'CHF',
                'symbol' => 'CHF',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 114,
                'name' => 'Dollars',
                'country' => 'Suriname',
                'code' => 'SRD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 115,
                'name' => 'Pounds',
                'country' => 'Syria',
                'code' => 'SYP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 116,
                'name' => 'New Dollars',
                'country' => 'Taiwan',
                'code' => 'TWD',
                'symbol' => 'NT$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 117,
                'name' => 'Baht',
                'country' => 'Thailand',
                'code' => 'THB',
                'symbol' => '฿',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 118,
                'name' => 'Dollars',
                'country' => 'Trinidad and Tobago',
                'code' => 'TTD',
                'symbol' => 'TT$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 119,
                'name' => 'Lira',
                'country' => 'Turkey',
                'code' => 'TRY',
                'symbol' => 'TL',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 120,
                'name' => 'Liras',
                'country' => 'Turkey',
                'code' => 'TRL',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 121,
                'name' => 'Dollars',
                'country' => 'Tuvalu',
                'code' => 'TVD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 122,
                'name' => 'Hryvnia',
                'country' => 'Ukraine',
                'code' => 'UAH',
                'symbol' => '₴',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 123,
                'name' => 'Pounds',
                'country' => 'United Kingdom',
                'code' => 'GBP',
                'symbol' => '£',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 124,
                'name' => 'Dollars',
                'country' => 'United States of America',
                'code' => 'USD',
                'symbol' => '$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 125,
                'name' => 'Pesos',
                'country' => 'Uruguay',
                'code' => 'UYU',
                'symbol' => '$U',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 126,
                'name' => 'Sums',
                'country' => 'Uzbekistan',
                'code' => 'UZS',
                'symbol' => 'лв',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 127,
                'name' => 'Euro',
                'country' => 'Vatican City',
                'code' => 'EUR',
                'symbol' => '€',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 128,
                'name' => 'Bolivares Fuertes',
                'country' => 'Venezuela',
                'code' => 'VEF',
                'symbol' => 'Bs',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 129,
                'name' => 'Dong',
                'country' => 'Vietnam',
                'code' => 'VND',
                'symbol' => '₫',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 130,
                'name' => 'Rials',
                'country' => 'Yemen',
                'code' => 'YER',
                'symbol' => '﷼',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 131,
                'name' => 'Zimbabwe Dollars',
                'country' => 'Zimbabwe',
                'code' => 'ZWD',
                'symbol' => 'Z$',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
