<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VacancyRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('vacancy_roles')->delete();

        \DB::table('vacancy_roles')->insert([
            [
                'id' => 1,
                'vacancy_category_id' => 1,
                'name' => 'Event Management',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'vacancy_category_id' => 1,
                'name' => 'Secretary / Assistant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'vacancy_category_id' => 1,
                'name' => 'Receptionist / Front Desk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'vacancy_category_id' => 1,
                'name' => 'Office Manager / Custodian',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'vacancy_category_id' => 1,
                'name' => 'Other - General Admin',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'vacancy_category_id' => 2,
                'name' => 'Custodian / Groundskeeper',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'vacancy_category_id' => 2,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'vacancy_category_id' => 2,
                'name' => 'Facilities Worker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'vacancy_category_id' => 2,
                'name' => 'Sanitation Engineer / Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'vacancy_category_id' => 2,
                'name' => 'Other - Cleaning / Janitorial',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'vacancy_category_id' => 3,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'vacancy_category_id' => 3,
                'name' => 'Doorkeeper',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'vacancy_category_id' => 3,
                'name' => 'Nightclub Security / Bouncer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'vacancy_category_id' => 3,
                'name' => 'Security Manager / Supervisor',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'vacancy_category_id' => 3,
                'name' => 'Other - Security',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'vacancy_category_id' => 4,
                'name' => 'Waitstaff / Server / Host(ess)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'vacancy_category_id' => 4,
                'name' => 'Cashier / Counter Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'vacancy_category_id' => 4,
                'name' => 'Chef / Sous chef / Baker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'vacancy_category_id' => 4,
                'name' => 'Line Cook / Prep Cook',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'vacancy_category_id' => 4,
                'name' => 'Bartender',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'vacancy_category_id' => 4,
                'name' => 'Restaurant / Kitchen Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'vacancy_category_id' => 4,
                'name' => 'Busboy',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'vacancy_category_id' => 4,
                'name' => 'Kitchen Staff',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'vacancy_category_id' => 4,
                'name' => 'Barista',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'vacancy_category_id' => 4,
                'name' => 'Doorkeeper',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'vacancy_category_id' => 4,
                'name' => 'Delivery / Shipping',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'vacancy_category_id' => 4,
                'name' => 'Receptionist / Front Desk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'vacancy_category_id' => 4,
                'name' => 'Supervisor',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'vacancy_category_id' => 4,
                'name' => 'Other - Restaurant/Bar/Café',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'vacancy_category_id' => 5,
                'name' => 'Concierge',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'vacancy_category_id' => 5,
                'name' => 'Receptionist / Front Desk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'vacancy_category_id' => 5,
                'name' => 'Room Service',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'vacancy_category_id' => 5,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'vacancy_category_id' => 5,
                'name' => 'Valet / Parking Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'vacancy_category_id' => 5,
                'name' => 'Night Auditor',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'vacancy_category_id' => 5,
                'name' => 'Porter / Bellhop',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'vacancy_category_id' => 5,
                'name' => 'Housekeeping',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'vacancy_category_id' => 5,
                'name' => 'Laundry',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'vacancy_category_id' => 5,
                'name' => 'Electrician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'vacancy_category_id' => 5,
                'name' => 'Plumber',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'vacancy_category_id' => 5,
                'name' => 'Maintainence - General',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'vacancy_category_id' => 5,
                'name' => 'Doorkeeper',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'vacancy_category_id' => 5,
                'name' => 'Waitstaff / Server / Host(ess)',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'vacancy_category_id' => 5,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'vacancy_category_id' => 6,
                'name' => 'Personal Care / Health Care',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'vacancy_category_id' => 6,
                'name' => 'Baby Sitting',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'vacancy_category_id' => 6,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'vacancy_category_id' => 6,
                'name' => 'Maintainence - General',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'vacancy_category_id' => 6,
                'name' => 'Plumber',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'vacancy_category_id' => 6,
                'name' => 'Electrician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'vacancy_category_id' => 6,
                'name' => 'Carpenter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'vacancy_category_id' => 6,
                'name' => 'Painter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'vacancy_category_id' => 6,
                'name' => 'Lawn Maintainence',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'vacancy_category_id' => 6,
                'name' => 'Other - Home',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'vacancy_category_id' => 6,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'vacancy_category_id' => 6,
                'name' => 'Pet Care',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'vacancy_category_id' => 7,
                'name' => 'Esthetician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'vacancy_category_id' => 7,
                'name' => 'Massage Therapist',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'vacancy_category_id' => 7,
                'name' => 'Nail Technician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'vacancy_category_id' => 7,
                'name' => 'Hairdresser / Barber',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'vacancy_category_id' => 7,
                'name' => 'Spa Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 62,
                'vacancy_category_id' => 7,
                'name' => 'Receptionist / Front Desk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'vacancy_category_id' => 7,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'vacancy_category_id' => 7,
                'name' => 'Other - Salon / Spa / Hairdresser',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'vacancy_category_id' => 7,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'vacancy_category_id' => 8,
                'name' => 'Doorkeeper',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'vacancy_category_id' => 8,
                'name' => 'Cashier / Counter Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 68,
                'vacancy_category_id' => 8,
                'name' => 'Sales Associate / Retail Assistant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 69,
                'vacancy_category_id' => 8,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 70,
                'vacancy_category_id' => 8,
                'name' => 'Stocker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'vacancy_category_id' => 8,
                'name' => 'Delivery / Shipping',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'vacancy_category_id' => 8,
                'name' => 'Retail Supervisor',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 73,
                'vacancy_category_id' => 8,
                'name' => 'Inventory Checker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 74,
                'vacancy_category_id' => 8,
                'name' => 'Other - Retail / Sales / Store',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 75,
                'vacancy_category_id' => 8,
                'name' => 'Merchandiser',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 76,
                'vacancy_category_id' => 8,
                'name' => 'Personal Shopper',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 77,
                'vacancy_category_id' => 8,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 78,
                'vacancy_category_id' => 9,
                'name' => 'Electrician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 79,
                'vacancy_category_id' => 9,
                'name' => 'Plumber',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 80,
                'vacancy_category_id' => 9,
                'name' => 'Carpenter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 81,
                'vacancy_category_id' => 9,
                'name' => 'Personal Care / Health Care',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 82,
                'vacancy_category_id' => 9,
                'name' => 'Painter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 83,
                'vacancy_category_id' => 9,
                'name' => 'Forklift Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 84,
                'vacancy_category_id' => 9,
                'name' => 'Truck Driver',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 85,
                'vacancy_category_id' => 9,
                'name' => 'Machinery Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 86,
                'vacancy_category_id' => 9,
                'name' => 'Crane Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 87,
                'vacancy_category_id' => 9,
                'name' => 'Cook',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 88,
                'vacancy_category_id' => 10,
                'name' => 'Machinery Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 89,
                'vacancy_category_id' => 10,
                'name' => 'Assembly Line Worker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 90,
                'vacancy_category_id' => 10,
                'name' => 'Technician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 91,
                'vacancy_category_id' => 10,
                'name' => 'Supervisor /Foreman',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 92,
                'vacancy_category_id' => 10,
                'name' => 'Forklift Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 93,
                'vacancy_category_id' => 10,
                'name' => 'Truck Driver',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 94,
                'vacancy_category_id' => 10,
                'name' => 'Clerk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 95,
                'vacancy_category_id' => 10,
                'name' => 'Loader',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 96,
                'vacancy_category_id' => 10,
                'name' => 'Stocker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 97,
                'vacancy_category_id' => 10,
                'name' => 'Packer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 98,
                'vacancy_category_id' => 10,
                'name' => 'Other - Manufacturing',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 99,
                'vacancy_category_id' => 11,
                'name' => 'Machinery Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 100,
                'vacancy_category_id' => 11,
                'name' => 'Stocker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 101,
                'vacancy_category_id' => 11,
                'name' => 'Loader',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 102,
                'vacancy_category_id' => 11,
                'name' => 'Clerk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 103,
                'vacancy_category_id' => 11,
                'name' => 'Truck Driver',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 104,
                'vacancy_category_id' => 11,
                'name' => 'Forklift Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 105,
                'vacancy_category_id' => 11,
                'name' => 'Receiver / Handler',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 106,
                'vacancy_category_id' => 11,
                'name' => 'Supervisor / Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 107,
                'vacancy_category_id' => 11,
                'name' => 'Other - Warehouse',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 108,
                'vacancy_category_id' => 11,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 109,
                'vacancy_category_id' => 11,
                'name' => 'Packer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 110,
                'vacancy_category_id' => 12,
                'name' => 'Construction Worker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 111,
                'vacancy_category_id' => 12,
                'name' => 'Inspector',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 112,
                'vacancy_category_id' => 12,
                'name' => 'Flooring Installer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 113,
                'vacancy_category_id' => 12,
                'name' => 'Electrician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 114,
                'vacancy_category_id' => 12,
                'name' => 'Plumber',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 115,
                'vacancy_category_id' => 12,
                'name' => 'Carpenter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 116,
                'vacancy_category_id' => 12,
                'name' => 'Surveyor',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 117,
                'vacancy_category_id' => 12,
                'name' => 'Glazier / Window Setter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 118,
                'vacancy_category_id' => 12,
                'name' => 'Painter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 119,
                'vacancy_category_id' => 12,
                'name' => 'Pipefitter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 120,
                'vacancy_category_id' => 12,
                'name' => 'Concrete Finisher',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 121,
                'vacancy_category_id' => 12,
                'name' => 'Tile Setter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 122,
                'vacancy_category_id' => 12,
                'name' => 'Brick Mason',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 123,
                'vacancy_category_id' => 12,
                'name' => 'Roofer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 124,
                'vacancy_category_id' => 12,
                'name' => 'Crane Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 125,
                'vacancy_category_id' => 12,
                'name' => 'Safety Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 126,
                'vacancy_category_id' => 12,
                'name' => 'Other - Construction',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 127,
                'vacancy_category_id' => 12,
                'name' => 'Machinery Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 128,
                'vacancy_category_id' => 12,
                'name' => 'Truck Driver',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 129,
                'vacancy_category_id' => 12,
                'name' => 'Forklift Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 130,
                'vacancy_category_id' => 12,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 131,
                'vacancy_category_id' => 13,
                'name' => 'Farm Worker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 132,
                'vacancy_category_id' => 13,
                'name' => 'Dairy / Livestock Worker',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 133,
                'vacancy_category_id' => 13,
                'name' => 'Farm Machinery Operator',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 134,
                'vacancy_category_id' => 13,
                'name' => 'Loader',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 135,
                'vacancy_category_id' => 13,
                'name' => 'Packer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 136,
                'vacancy_category_id' => 13,
                'name' => 'Delivery / Shipping',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 137,
                'vacancy_category_id' => 14,
                'name' => 'Personal Trainer / Trainer',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 138,
                'vacancy_category_id' => 14,
                'name' => 'Physical Therapist',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 139,
                'vacancy_category_id' => 14,
                'name' => 'Massage Therapist',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 140,
                'vacancy_category_id' => 14,
                'name' => 'Lifeguard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 141,
                'vacancy_category_id' => 14,
                'name' => 'Group Instructor / Fitness Instructor',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 142,
                'vacancy_category_id' => 14,
                'name' => 'Assistant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 143,
                'vacancy_category_id' => 14,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 144,
                'vacancy_category_id' => 14,
                'name' => 'Receptionist / Front Desk',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 145,
                'vacancy_category_id' => 14,
                'name' => 'Other - Sports / Fitness',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 146,
                'vacancy_category_id' => 15,
                'name' => 'Call Center / Customer Service Rep.',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 147,
                'vacancy_category_id' => 15,
                'name' => 'Personal Service Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 148,
                'vacancy_category_id' => 15,
                'name' => 'Sales',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 149,
                'vacancy_category_id' => 16,
                'name' => 'Truck Driver',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 150,
                'vacancy_category_id' => 16,
                'name' => 'Car Driver / Limo Driver',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 151,
                'vacancy_category_id' => 16,
                'name' => 'Delivery / Shipping',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 152,
                'vacancy_category_id' => 17,
                'name' => 'Usher',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 153,
                'vacancy_category_id' => 17,
                'name' => 'Ticketing',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 154,
                'vacancy_category_id' => 17,
                'name' => 'Character Artist',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 155,
                'vacancy_category_id' => 17,
                'name' => 'Box Office Assistant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 156,
                'vacancy_category_id' => 17,
                'name' => 'Stage & Prop Support',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 157,
                'vacancy_category_id' => 17,
                'name' => 'Call Center / Customer Service Rep.',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 158,
                'vacancy_category_id' => 17,
                'name' => 'Secretary / Assistant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 159,
                'vacancy_category_id' => 17,
                'name' => 'Food Kiosk / Food Stand Support',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 160,
                'vacancy_category_id' => 17,
                'name' => 'Security Guard',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 161,
                'vacancy_category_id' => 17,
                'name' => 'Projectionist',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 162,
                'vacancy_category_id' => 17,
                'name' => 'Electrician',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 163,
                'vacancy_category_id' => 17,
                'name' => 'Plumber',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 164,
                'vacancy_category_id' => 17,
                'name' => 'Carpenter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 165,
                'vacancy_category_id' => 17,
                'name' => 'Painter',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 166,
                'vacancy_category_id' => 17,
                'name' => 'Cleaner / Attendant',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 167,
                'vacancy_category_id' => 17,
                'name' => 'Facilities Manager',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 168,
                'vacancy_category_id' => 17,
                'name' => 'Other - Theatre & Ent.',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 169,
                'vacancy_category_id' => 18,
                'name' => 'General Jobs',
                'is_active' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
